name: Publish
on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5

      - name: Build binaries
        run: cargo build --profile release

      - name: Run tests
        run: cargo test --profile release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: prompt
          path: target/release/prompt
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: prompt
          path: prompt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: prompt
